### ISSUE TITLE
Please compile a jar for download

### ISSUE THREAD

**Issue by Hacon** [devinfrench/runelite-ext#5]
tried a few times to compile this had no problems with base runelite or runelite ++ but this keeps giving an error after maven is run when i go to launch the client about the uuid. It would be great for a finished link

**Comment by Hacon** [comment]
"C:\Program Files\Java\jdk1.8.0_211\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2\lib\idea_rt.jar=53248:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_211\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\rt.jar;C:\Trial\runelite-client\target\classes;C:\Users\ben_s\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\ben_s\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\ben_s\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\ben_s\.m2\repository\net\sf\jopt-simple\jopt-simple\5.0.1\jopt-simple-5.0.1.jar;C:\Users\ben_s\.m2\repository\com\google\guava\guava\23.2-jre\guava-23.2-jre.jar;C:\Users\ben_s\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\ben_s\.m2\repository\com\google\errorprone\error_prone_annotations\2.0.18\error_prone_annotations-2.0.18.jar;C:\Users\ben_s\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\ben_s\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\ben_s\.m2\repository\com\google\inject\guice\4.1.0\guice-4.1.0-no_aop.jar;C:\Users\ben_s\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\ben_s\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\ben_s\.m2\repository\com\google\code\gson\gson\2.8.5\gson-2.8.5.jar;C:\Users\ben_s\.m2\repository\net\runelite\pushingpixels\substance\8.0.02\substance-8.0.02.jar;C:\Users\ben_s\.m2\repository\net\runelite\pushingpixels\trident\1.5.00\trident-1.5.00.jar;C:\Users\ben_s\.m2\repository\org\apache\commons\commons-text\1.2\commons-text-1.2.jar;C:\Users\ben_s\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;C:\Trial\runelite-api\target\classes;C:\Trial\runescape-api\target\classes;C:\Users\ben_s\.m2\repository\net\runelite\injected-client\1.4.12-SNAPSHOT\injected-client-1.4.12-20180816.110906-32.jar;C:\Trial\http-api\target\classes;C:\Users\ben_s\.m2\repository\com\squareup\okhttp3\okhttp\3.7.0\okhttp-3.7.0.jar;C:\Users\ben_s\.m2\repository\com\squareup\okio\okio\1.12.0\okio-1.12.0.jar;C:\Users\ben_s\.m2\repository\net\runelite\discord\1.0\discord-1.0.jar;C:\Users\ben_s\.m2\repository\net\java\dev\jna\jna\4.5.1\jna-4.5.1.jar" net.runelite.client.RuneLite
2019-05-17 08:15:28 [main] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-05-17 08:15:28 [pool-2-thread-1] WARN  n.runelite.http.api.item.ItemClient - Error looking up prices: Not Found
2019-05-17 08:15:29 [main] WARN  n.r.client.ClientSessionManager - error opening session
java.io.IOException: java.lang.IllegalArgumentException: Invalid UUID string: <html><head><title>Apache
	at net.runelite.http.api.session.SessionClient.open(SessionClient.java:59)
	at net.runelite.client.ClientSessionManager.start(ClientSessionManager.java:58)
	at net.runelite.client.RuneLite.start(RuneLite.java:254)
	at net.runelite.client.RuneLite.main(RuneLite.java:217)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: <html><head><title>Apache
	at java.util.UUID.fromString(UUID.java:194)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:550)
	at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:543)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:865)
	at net.runelite.http.api.session.SessionClient.open(SessionClient.java:55)
	... 3 common frames omitted
2019-05-17 08:15:29 [main] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.reflect.InvocationTargetException: null
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at net.runelite.client.ui.ClientUI.open(ClientUI.java:242)
	at net.runelite.client.RuneLite.start(RuneLite.java:257)
	at net.runelite.client.RuneLite.main(RuneLite.java:217)
Caused by: eh: null
	at ai.s(ai.java:102)
	at client.init(client.java:746)
	at net.runelite.client.ui.ClientPanel.<init>(ClientPanel.java:53)
	at net.runelite.client.ui.ClientUI.lambda$open$5(ClientUI.java:276)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
